### ISSUE TITLE
Devito interaction with LDFLAGS generates unexpected errors

### ISSUE THREAD

**Issue by NewtonSander** [devitocodes/devito#2111] opened 2023-04-17 17:00 UTC
Firstly, I want to thank you for all the amazing work you have done on this package. 

Here's a script to reproduce the issue:

``` py devito_LDFLAGS.py
from devito import Eq, Grid, TimeFunction, Operator, configuration

configuration['language'] = 'openmp'

grid = Grid(shape=(3, 3))
u_new = TimeFunction(name='u_new', grid=grid, space_order=(4, 3, 1))
equation = Eq(u_new.forward, u_new + 2)
op = Operator(equation, opt='noop')

# here the compiler is invoked
op.apply(time_M=2)
```

The above script runs just fine if no LDFLAGS are set but fails with an unexpected error otherwise:
```
devito % python devito_LDFLAGS.py 
Operator `Kernel` ran in 0.01 s
```

failure:
```
devito % LDFLAGS="-L/usr/local/lib" python devito_LDFLAGS.py
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
FAILED compiler invocation:gcc -O3 -g -march=native -fPIC -Wall -std=c99 -L/usr/local/lib -fopenmp /var/folders/57/_b49l46122jgsn1lvw_fffd80000gn/T/devito-jitcache-uid501/6a5cff557283f0782ecc882c900718eaa08e2769.c -lm -o /var/folders/57/_b49l46122jgsn1lvw_fffd80000gn/T/devito-jitcache-uid501/6a5cff557283f0782ecc882c900718eaa08e2769.dylib
Traceback (most recent call last):
  File "/Users/newtonsander/workspace/bci/devito/devito_LDFLAGS.py", line 11, in <module>
    op.apply(time_M=2)
  File "/Users/newtonsander/workspace/bci/devito/devito/operator/operator.py", line 757, in apply
    cfunction = self.cfunction
  File "/Users/newtonsander/workspace/bci/devito/devito/operator/operator.py", line 639, in cfunction
    self._jit_compile()
  File "/Users/newtonsander/workspace/bci/devito/devito/operator/operator.py", line 624, in _jit_compile
    recompiled, src_file = self._compiler.jit_compile(self._soname,
  File "/Users/newtonsander/workspace/bci/devito/devito/arch/compiler.py", line 319, in jit_compile
    _, _, _, recompiled = compile_from_string(self, target, code, src_file,
  File "/Users/newtonsander/workspace/bci/devito/.venv/lib/python3.9/site-packages/codepy/jit.py", line 433, in compile_from_string
    toolchain.build_extension(ext_file, source_paths, debug=debug)
  File "/Users/newtonsander/workspace/bci/devito/.venv/lib/python3.9/site-packages/codepy/toolchain.py", line 210, in build_extension
    raise CompileError("module compilation failed")
codepy.CompileError: module compilation failed
```

**Comment by NewtonSander** [comment] 2023-04-19 14:52
> Hi @NewtonSander, I see you are using clang as a default compiler? If you run the same code with DEVITO_ARCH=gcc, it should not fail right? Can you try with DEVITO_ARCH=clang?

Hi! Yes, it works on both:
```
DEVITO_ARCH=clang LDFLAGS="-L/usr/local/lib" python devito_LDFLAGS.py
Operator `Kernel` ran in 0.01 s
```
```
DEVITO_ARCH=gcc LDFLAGS="-L/usr/local/lib" python devito_LDFLAGS.py
Operator `Kernel` ran in 0.01 s

```

**Comment by georgebisbas** [comment] 2023-04-19 15:46
Can you also run with DEVITO_LOGGING=DEBUG to check the log output?
The issue is that you where running with your default compiler which, is clang, and using the default flags which are the GCC ones.

**Comment by NewtonSander** [comment] 2023-04-19 16:22
> 

These are the logs:
```
DEVITO_LOGGING=DEBUG  LDFLAGS="-L/usr/local/lib" python devito_LDFLAGS.py
Operator `Kernel` generated in 0.10 s
  * lowering.IET: 0.06 s (63.6 %)
     * specializing.IET: 0.03 s (31.8 %)
        * optimize_halospots: 0.02 s (21.2 %)
  * lowering.uIET: 0.02 s (21.2 %)
  * lowering.Expressions: 0.02 s (21.2 %)
Flops reduction after symbolic optimization: [1 --> 1]
Allocating host memory for u_new(2, 7, 7) [392 B]
gcc -O3 -g -march=native -fPIC -Wall -std=c99 -L/usr/local/lib -fopenmp /var/folders/57/_b49l46122jgsn1lvw_fffd80000gn/T/devito-jitcache-uid501/6a5cff557283f0782ecc882c900718eaa08e2769.c -lm -o /var/folders/57/_b49l46122jgsn1lvw_fffd80000gn/T/devito-jitcache-uid501/6a5cff557283f0782ecc882c900718eaa08e2769.dylib
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
FAILED compiler invocation:gcc -O3 -g -march=native -fPIC -Wall -std=c99 -L/usr/local/lib -fopenmp /var/folders/57/_b49l46122jgsn1lvw_fffd80000gn/T/devito-jitcache-uid501/6a5cff557283f0782ecc882c900718eaa08e2769.c -lm -o /var/folders/57/_b49l46122jgsn1lvw_fffd80000gn/T/devito-jitcache-uid501/6a5cff557283f0782ecc882c900718eaa08e2769.dylib
Traceback (most recent call last):
  File "/Users/newtonsander/workspace/bci/devito/devito_LDFLAGS.py", line 11, in <module>
    op.apply(time_M=2)
  File "/Users/newtonsander/workspace/bci/devito/devito/operator/operator.py", line 757, in apply
    cfunction = self.cfunction
  File "/Users/newtonsander/workspace/bci/devito/devito/operator/operator.py", line 639, in cfunction
    self._jit_compile()
  File "/Users/newtonsander/workspace/bci/devito/devito/operator/operator.py", line 624, in _jit_compile
    recompiled, src_file = self._compiler.jit_compile(self._soname,
  File "/Users/newtonsander/workspace/bci/devito/devito/arch/compiler.py", line 319, in jit_compile
    _, _, _, recompiled = compile_from_string(self, target, code, src_file,
  File "/Users/newtonsander/workspace/bci/devito/.venv/lib/python3.9/site-packages/codepy/jit.py", line 433, in compile_from_string
    toolchain.build_extension(ext_file, source_paths, debug=debug)
  File "/Users/newtonsander/workspace/bci/devito/.venv/lib/python3.9/site-packages/codepy/toolchain.py", line 210, in build_extension
    raise CompileError("module compilation failed")
codepy.CompileError: module compilation failed
```

**Comment by mloubout** [comment] 2023-04-20 00:29
Is this osx (M1)?

**Comment by NewtonSander** [comment] 2023-04-20 00:36
> Is this osx (M1)?

no, it's an intel mac

**Comment by georgebisbas** [comment] 2023-04-20 09:52
So it looks like this is fine by specifying either clang or gcc as the arch. I am closing this issue for now; feel free to reopen it if needed, or you can always join and ask on slack: https://join.slack.com/t/devitocodes/shared_invite/zt-gtd2yxj9-Y31YKk_7lr9AwfXeL2iMFg

**Closed by georgebisbas** 2023-04-20 09:52 UTC

**Comment by NewtonSander** [comment] 2023-04-20 14:04
@georgebisbas I was wondering what could be done to make debugging this kind of problem easier, maybe the compiler could log the decisions made and then the user could more easily understand what's going on?
I am guessing most people could have LDFLAGS set in their environment variables not thinking it could cause this type of side effect...

**Comment by mloubout** [comment] 2023-04-20 14:19
The main thing is, if you do not set `DEVITO_ARCH` then by default devito expects a `CustomCompiler` wich will use your environment (CC, CXX, LDFLAGS, CFLAGS) while if you set `DEVITO_ARCH` then it will use the specified compiler and infer all the flags/.... and ignore your environment (CC, CXX, LDFLAGS, CFLAGS).

So basically ` LDFLAGS="-L/usr/local/lib"` this uses `CustomCompiler` and your `LDFLAGS` and error but any `DEVITO_ARCH=... LDFLAGS=....` will ignore your `LDFLAGS` and instead setup all the libs/glags needed.
