### ISSUE TITLE
Problem with installation via Docker on Win10

### ISSUE THREAD

**Issue by kamranabbas20** [devitocodes/devito#1792] opened 2021-11-04 11:30 UTC
I am having a trouble installing `devito` with **Docker** on Windows 10, as I am facing the following error output after running this line: `docker-compose run devito /tests`

```
Creating devito_devito_run ... done
/usr/bin/env: ‘bash\r’: No such file or directory
ERROR: 127
```

I have followed the instructions from this [web-page](https://github.com/devitocodes/devito/wiki/Installation-Issues):

"Ensure that `git config --global core.autocrlf false` is set to prevent modification of line endings when cloning the repository

before cloning git repo, which didn't spit out any errors, but upon running  `docker-compose run devito /tests` I got the error mentioned above.

**Comment by FabioLuporini** [comment] 2021-11-10 14:25
@navjotk any idea?

**Comment by mloubout** [comment] 2021-11-10 14:29
Where are you running this command? I am not sure if this work on a windows terminal/power-shell

**Comment by hembramsasmita** [comment] 2021-11-11 05:18
I am also facing the same issue. I have used windows terminal to run these commands. Please give some suggestion.

**Comment by mloubout** [comment] 2021-11-11 15:08
>I have used windows terminal to run these commands. 

These commands are for linux/osx terminal I don't think you can run them in a Microsoft terminal.  So you can either
- use WSL and run these commands in it
- Install docker-desktop for windows and use docker-compose within the app

**Comment by hembramsasmita** [comment] 2021-11-12 14:39
I have tried running those commands on WSL, and got same error.
I also tried the following:
 
docker-compose up -d devito
Starting devito_devito_1 ... done

docker-compose run -d devito /bin/bash
Creating devito_devito_run ... done
devito_devito_run_fb27c4ca90d9
 
docker-compose run -d devito /tests
Creating devito_devito_run ... done
devito_devito_run_4a2297210f7a

Is there any alternative to solve this issue? Please suggest.

**Comment by mloubout** [comment] 2021-11-12 14:48
Hum looks like there is bad characters in your `entry point.sh` script. I checked on y machine and the `\r` is not here so not sure what happened. You can always try to fix the files with `dos2unix` and then rerun docker-compose.

Did you modify anything in the docker directory?

**Comment by hembramsasmita** [comment] 2022-01-07 04:41
The installation problem is solved. Thank you.

**Comment by mloubout** [comment] 2022-01-07 04:42
Good to hear, closing.

**Closed by mloubout** 2022-01-07 04:42 UTC
Labels: installation

**Comment by navjotk** [comment] 2022-01-07 15:43
Late to the party but I wanted to add my thoughts for people who run into this issue later. 

Reading this, I think the issue was caused by git's default behaviour of automatically changing line endings from linux style (only \n), which is what all files in our repo follow, to windows-style (\r\n) on checkout on a windows system. This then clashes with linux's (running inside docker) expectation of "\n" line endings. 

The relevant line in our instructions [here](https://github.com/devitocodes/devito/wiki/Installation-Issues) is this command:
```
git config --global core.autocrlf false
```

I believe issuing this command before cloning the repo avoids this issue entirely. It can also be later fixed by using `dos2unix` as @mloubout suggested above.
