### ISSUE TITLE
Different results with MPI when halo larger than rank domain

### ISSUE THREAD

**Issue by mloubout** [devitocodes/devito#1331] opened 2020-06-03 20:06 UTC
the following results produces different results with and without mpi with more than 4 workers

```
import numpy as np
from devito import Grid, Function, TimeFunction, Eq, Operator, norm

udata = np.arange(300).reshape(3, 10, 10)

grid = Grid((10, 10))

u = TimeFunction(name="u", grid=grid, time_order=2, space_order=8)
u.data[:] = udata
w = Function(name="w", grid=grid, space_order=8)

Operator(Eq(w, u.dx))(time_M=5)

print(norm(w))
```

**Comment by rhodrin** [comment] 2020-06-04 09:17
I think the above behaviour is expected. You start to see errors in cases where you have `inhalo`'s hitting `outhalo`'s which should be triggering a warning. But when I wrote the code I missed this case. See: https://github.com/devitocodes/devito/blob/62d14742987b6f8fc262eda54fda39ecdcbffee6/devito/types/dense.py#L319

Will correct and update the warning when I get the chance. But I don't think this is an MFE for the original problem.

Also, can we double check whether the problem is with 'MPI' workings or with the norm? @jkwashbourne, if you get the chance, you could gather all the data on a single rank and hit it with `np.linalg.norm` to see what you get? When you get around to this, hit me up on slack if you need and I can give you some code for the gather.

**Comment by mloubout** [comment] 2020-06-04 19:55
I found the problem, unrelated to this. Tag this issue when you update the warning

**Comment by FabioLuporini** [comment] 2020-07-03 07:31
added further warning in #1370 , closing this

**Closed by FabioLuporini** 2020-07-03 07:31 UTC
Labels: bug-py-minor
