### ISSUE TITLE
Add action: performance regression on push to PR

### ISSUE THREAD

**Issue by EdCaunt** [devitocodes/devito#1055] opened 2020-01-09 11:29 UTC

**Comment by navjotk** [comment] 2020-01-09 15:14
@FabioLuporini has made some progress on this. Anyone else working on this - Talk to him before taking any steps towards this.

**Comment by FabioLuporini** [comment] 2020-01-28 14:26
this is work in progress. 

I'm currently using a fork of devito. Here is the latest diff:

https://github.com/devitocodes/devito/compare/master...FabioLuporini:master

For performance regression, we will be using Airspeed Velocity. 

Key steps so far:
- [install ASV](https://github.com/FabioLuporini/devito/blob/master/.github/workflows/asv.yml#L37) in the conda environment
- Get a [list](https://github.com/FabioLuporini/devito/blob/master/.github/workflows/asv.yml#L41) of the last 10 merge-into-master commits. We want to run the performance regression suite on each of them
- [Configure ASV](https://github.com/FabioLuporini/devito/blob/master/.github/workflows/asv.yml#L43)
- [Run the benchmark suite](https://github.com/FabioLuporini/devito/blob/master/.github/workflows/asv.yml#L47)
- Create the [results (html format)](https://github.com/FabioLuporini/devito/blob/master/.github/workflows/asv.yml#L58)
- [Trying to push them](https://github.com/FabioLuporini/devito/blob/master/.github/workflows/asv.yml#L73) on our web site -- here's were we got stuck. We have [this deployment related issue](https://github.com/FabioLuporini/devito/runs/387242154#step:12:16)

Note that we still have to write a proper benchmark suite ! 

Also note that #1074 does **not** contain yet all of the updates that I have pushed to [my fork](https://github.com/FabioLuporini/devito/blob/master/.github/workflows/asv.yml)

the reason I'm using a fork is that this way I can use CI as I need the `master` branch to work with ASV

**Comment by FabioLuporini** [comment] 2020-04-29 06:34
fixed by #1074

**Closed by FabioLuporini** 2020-04-29 06:34 UTC
Labels: DevOps
