### ISSUE TITLE
Solution in example on internal nodes converge with 0 with high grid density in poisson and laplace examples.

### ISSUE THREAD

**Issue by RomanLopezFerber** [devitocodes/devito#1568] opened 2021-01-25 15:20 UTC
Hello,

I find a strange behavior in the examples I tried on examples/cfd/Laplace and Poisson (using the hand-coded method) :
The higher the grid resolution is, the more the internal nodes are converging to 0, which seem to be not physical. Could someone tell me what is going on these examples ?

Here is the laplace example with nx = ny = 500
![image](https://user-images.githubusercontent.com/77978662/105724970-b2eae080-5f28-11eb-91a1-e051a538e36e.png)

And here with nx = ny = 100

![image](https://user-images.githubusercontent.com/77978662/105725300-170da480-5f29-11eb-90e1-b75c769eafc6.png)

Thank you for all the documentation around this library and thank you in advance for your help.

Roman

**Comment by FabioLuporini** [comment] 2021-01-26 08:44
This seems to be more of a math question than a devito question. If you increase the number of grid points while keeping the rest fixed (including the physical extent of the grid and the source location), that should be the expected behavior

**Comment by RomanLopezFerber** [comment] 2021-01-27 13:47
Sorry if my question was not in the field of devito, I felt it was, as my question is still related to physics. 
To clarify my question my reasoning is the following :
Let us consider an area of 1km by 2km.
The space is discretised in Nx * Ny points to approximate the continuous space. And therefore we compute with the finite diffference method to approximate a continuous solution. So to me, if only the grid resolution vary (not the physical size of the area), we should converge to a continuous solution. And when above a given resolution the result should not change any more, is it not right ?

I will try soon with devito this example, I used the explicitly written method of the example for the moment.

**Comment by FabioLuporini** [comment] 2022-09-23 06:58
Closing. Feel free to use Slack for this sort of higher level questions

**Closed by FabioLuporini** 2022-09-23 06:58 UTC
