### ISSUE TITLE
Facing issue while using command 'conda env create -f environment-dev.yml' for devito installation on centOS 7 gen 2

### ISSUE THREAD

**Issue by sbapubha** [devitocodes/devito#1904] opened 2022-04-13 06:21 UTC
ERROR: Command errored out with exit status 1: /home/Devito/miniconda3/envs/devito/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-mfrw2r8h/pyrevolve_6f691ebff52244e18377fac7c7fe58fc/setup.py'"'"'; __file__='"'"'/tmp/pip-install-mfrw2r8h/pyrevolve_6f691ebff52244e18377fac7c7fe58fc/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-4932e295/install-record.txt --single-version-externally-managed --compile --install-headers /home/Devito/miniconda3/envs/devito/include/python3.10/pyrevolve Check the logs for full command output.
                                                                                                                                                                               failed

CondaEnvException: Pip failed

**Comment by mloubout** [comment] 2022-04-13 12:20
Is that the full error?

Also you can put the trace in a code block with triple quotes instead of plain text to make it easier to read, i.e 
```
error trace
here
```

**Comment by sbapubha** [comment] 2022-04-15 04:57
Thanks for reply 

Now getting another error
When I enter pip command it show various option 
How to find devito project path?

(base) [Devito@DevitoVM ~]$ pip install -e

Usage:
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

-e option requires 1 argument

**Comment by FabioLuporini** [comment] 2022-04-26 07:19
Take a look at this: https://github.com/devitocodes/devito/wiki/FAQ#how-do-you-run-the-unit-tests-from-the-command-line

Glad to see the issue is resolved; closing...

**Closed by FabioLuporini** 2022-04-26 07:19 UTC
