### ISSUE TITLE
"grad" function produces incorrect results for argument with multiple functions

### ISSUE THREAD

**Issue by nogueirapeterson** [devitocodes/devito#1432] opened 2020-08-17 13:04 UTC
Hi guys,

`grad` function produces incorrect values when its argument involves operation with several functions. 
@mloubout the example below shows the computation of the `grad` with a precomputed argument vs the computation of the grad operating directly on the argument. The results are different.

Furthermore, the `grad` results with a pre-computed argument work fine in the adjoint visco-acoustic equation. While operating directly, it produces NAN.

```
from devito import *
import numpy as np
shape = (25, 25)
space_order = 4
grid = Grid(shape=shape)
p1 = TimeFunction(name="p1", grid=grid, time_order=1, space_order=space_order, staggered=NODE)
A = TimeFunction(name="A", grid=grid, time_order=1, space_order=space_order, staggered=NODE, parameter=True)
A._data_with_outhalo[:] = np.random.random()
B = TimeFunction(name="B", grid=grid, time_order=1, space_order=space_order, staggered=NODE, parameter=True)
B._data_with_outhalo[:] = np.random.random()
av1 = VectorTimeFunction(name="av1", grid=grid, time_order=1, space_order=space_order)
av2 = VectorTimeFunction(name="av2", grid=grid, time_order=1, space_order=space_order)
# Operator with precomputed (1.+A)*B
eq1 = Eq(p1, ((1.+A)*B))
eq2 = Eq(av1, grad(p1))
op = Operator([eq1, eq2])
op.apply(time_M=0)
# Operator with grad((1.+A)*B) directly
eq3 = Eq(av2, grad((1.+A)*B))
op2 = Operator([eq3])
op2.apply(time_M=0)
print("av1.data")
print("------------------------------")
print(av1[0].data[:], av1[1].data[:], sep="\n")
print("av2.data")
print("------------------------------")
print(av2[0].data[:], av2[1].data[:], sep="\n")
print("diff")
print("------------------------------")
print(av1[0].data[:]-av2[0].data[:], av1[1].data[:]-av2[1].data[:], sep="\n")
```
Thanks. I hope I've helped.

**Comment by mloubout** [comment] 2020-08-17 13:33
Looking at the generated code, everything looks sane. I think the only difference comes from the halo and is probably related to #1250 . `av1` and `av2` match within the domain it's only the edge points that have different values.
In the halo `p1` will be zero while `(1.+A)*B` will not sid `data_with_outhalo` in initialized there which is why you get different values.

If you do `B.data[:] = np.random.random(), A.data[:] = np.random.random()` you get the same values in both cases (within floating point)

**Comment by nogueirapeterson** [comment] 2020-08-17 14:49
Got it. So it's a problem in the halo as in # 1250.
Okay, thanks for the feedback.

**Comment by FabioLuporini** [comment] 2020-09-03 12:47
closing as duplicate of #1250

**Closed by FabioLuporini** 2020-09-03 12:47 UTC
